### ISSUE TITLE
Add About Us section

### ISSUE THREAD

**Issue by tshiUCSB** [sbhacks-org/sbhacks-site#21]
Background gradient colors: from #2c819e (registered as sea-dark in Tailwind) to #3966a6 (not registered)
Font color: seafoam
Content:
"SB Hacks is a 36-hour hackathon hosted annually by students at the University of California, Santa Barbara. Normally the event takes place on campus, but this year, we are going digital! SB Hacks aims to expose college students to the technology industry and provide the necessary resources to get hands-on experience in coding. Whether you are a first-time coder or a seasoned hacker, we encourage you to enter SB Hacks with enthusiasm and curiosity. Our hope is that you challenge yourself with a fun project, learn something new along the way, and are proud of what you have accomplished at the end of it all."
Section height should be at least 100vh

**Comment by soohyunchoi** [comment]
#22
